public class trycatchcode{
    public static void main (String args[]){
        int a=0;
        int b=0;
        int result;
        try{
        result=a/b;
            System.out.println("result");
    }catch (ArithmeticException e){
        System.out.println("exception caught:it a cannot divided by b");
    }
        System.out.println("program continues after try catch block");
    }
}
